language: go
go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "tip"
services:
  - postgresql
addons:
  postgresql: "9.6"
  hosts:
    - postgres
before_script:
  - psql -U postgres < migrations/create_table_logs.sql
